name: Test_Automated_Operator_Automation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # 8:00 AM Colombia (UTC-5)
    - cron: '0 17 * * *' # 12:00 PM Colombia (UTC-5)
    - cron: '0 23 * * *' # 6:00 PM Colombia (UTC-5)

jobs:
  operator_automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman & reporters
        run: npm install -g newman newman-reporter-htmlextra

      - name: Verify Environment File Exists
        run: |
          if [ ! -f "operator_automation/Mock_Operator.postman_environment.json" ]; then
            echo "Error: Environment file not found!"
            exit 1
          fi

      - name: Debug File Listing
        run: ls -l operator_automation/

      - name: Run Postman Collection
        run: |
          newman run "operator_automation/Mock_Operator.postman_collection.json" \
            -e "operator_automation/Mock_Operator.postman_environment.json" \
            -r json,htmlextra \
            --reporter-json-export newman-report.json \
            --reporter-htmlextra-export newman-report.html

      - name: Upload Newman Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: operator-automation-report
          path: |
            newman-report.html
            newman-report.json
