name: Run Newman Tests

on:
  push:
    branches:
      - main  # revisa que tu rama se llame así, no MAIN en mayúsculas
  workflow_dispatch:

jobs:
  newman_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection
        run: |
          newman run mock_operator.postman_collection.json \
          -e mock_operator.postman_environment.json \
          --reporters cli,json --reporter-json-export results.json

      - name: Upload results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: newman-results
          path: results.json
